name: Terraform Core

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/core/**"
      - ".github/workflows/terraform-core.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  terraform-core:
    name: Terraform core plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/core

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::110735825932:role/ai-callcenter-poc-github-actions-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan
